version: '3'
services:
  server:
    image: codeberg.org/forgejo/forgejo:1.20
    container_name: forgejo
    environment:
      - USER_UID=1030
      - USER_GID=65536
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
      - FORGEJO__server__DOMAIN=code.${ROOT_DOMAIN?Please supply a root domain.}
    restart: unless-stopped
    networks:
      - forgejo
    volumes:
      - ${ROOT_FOLDER?Please supply a root folder.}/forgejo:/data
      - ./forgejo.ini:/etc/forgejo/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.rule=Host(`code.${ROOT_DOMAIN?Please supply a root domain name.}`)
      - traefik.http.routers.forgejo.tls.certresolver=patches
      - traefik.http.services.forgejo.loadbalancer.server.port=3000
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks:
      - forgejo
    volumes:
      - ${ROOT_FOLDER?Please supply a root folder.}/postgres:/var/lib/postgresql/data
networks:
  forgejo:
  traefik:
    external: true
