http:
  routers:
    beryl-dsm:
      rule: "Host(`beryl.patches.systems`)"
      service: beryl-dsm
      tls:
        certResolver: patches
    beryl-portainer:
      rule: "Host(`portainer.beryl.patches.systems`)"
      service: beryl-portainer
      tls:
        certResolver: patches
  services:
    beryl-dsm:
      loadBalancer:
        servers:
          - url: "http://10.0.0.3:5000"
    beryl-portainer:
      loadBalancer:
        servers:
          - url: "http://10.0.0.3:9000"
